### ISSUE TITLE
Error: unexpected HTTP response code 307 when accessing https://api.github.com/repos/carrotIndustries/horizon-pool/pulls

### ISSUE THREAD

**Issue by krasimirk** [horizon-eda/horizon#268]
This error is shown when I create a new pull request from the pool manager:
![image](https://user-images.githubusercontent.com/1655094/58043845-f895ba00-7b46-11e9-9848-abf96691fb48.png)

However the pull request was visible in the github web site.

**Comment by carrotIndustries** [comment]
Are you using https://github.com/horizon-eda/horizon/commit/dfa9fad3d884b31c1a987e3d99dd3cf84acdd9a6 or newer?

**Comment by krasimirk** [comment]
How to find out?
There is no "About" dialog.
I checked out before one month from the git and compiled manually.

**Comment by carrotIndustries** [comment]
It's at the bottom of the start screen (the one showing recent pools and projects)

**Comment by krasimirk** [comment]
![image](https://user-images.githubusercontent.com/1655094/58044546-b1102d80-7b48-11e9-8904-2d285a541da2.png)
Does not seems like check sum for git revision.

**Comment by carrotIndustries** [comment]
> Are you using dfa9fad or newer?

You're using a version older than that. That commit should have fixed this issue.

**Comment by atoav** [comment]
If this has been already fixed, it can be closed. @krasimirk did it solve your problems?

**Comment by krasimirk** [comment]
I will try tonight to upgrade to the latest sources and to check if it fixed.

**Comment by atoav** [comment]
Ahh no pressure, just thought it might have been forgotten, because the last post was 8 days ago : )

**Comment by krasimirk** [comment]
![horizon_version](https://user-images.githubusercontent.com/1655094/58492216-24352780-8179-11e9-9ee1-8ea34dd5e398.png)
![same_error](https://user-images.githubusercontent.com/1655094/58492221-26978180-8179-11e9-9d6f-6bf0c99abdac.png)
Not fixed yet.
Let me now if you want more information, debug info or whatsoever.
Regards,
Krasimir Kostadinov

**Comment by carrotIndustries** [comment]
Sorry for letting this sit for so long, but that's likely caused by moving the pool repo to the new organisation. Either manually update the remote to point to the new repo or just re-download the pool and and copy your modifications to the new one.

**Comment by carrotIndustries** [comment]
most likely fixed by now
